#!/usr/bin/env python3

import sys
from pathlib import Path

core_path = Path(__file__).parent / "core"
sys.path.append(str(core_path))

# Imports
from core.mcrits import start

if __name__ == "__main__":
    code = start(sys.argv)
    sys.exit(code) 


